const guide = (title, text) => `<details class="help-guide"><summary>${title}</summary><p>${text}</p><a href="https://wa.me/554333759800?text=Preciso%20de%20orienta%C3%A7%C3%A3o%20sobre%20um%20sinistro" target="_blank" rel="noopener">Falar com a Originalli ↗</a></details>`;

export const centralBody = `
<section class="inner-hero central-hero"><div class="container"><p class="breadcrumb"><a href="../">Início</a><span>›</span>Central Originalli</p><p class="eyebrow dark">Assistência e serviços</p><h1>Ajuda para o momento<br>em que você precisa.</h1><p class="inner-hero-lead">Canais de atendimento, orientações para sinistros e consultas úteis, em um só lugar.</p><nav class="central-shortcuts" aria-label="Serviços da Central"><a href="#emergencia">Emergência</a><a href="#orientacoes">Sinistros</a><a href="#fipe">Tabela FIPE</a><a href="#bo">Boletim de ocorrência</a><a href="../contrate-online/">Cotações</a><a href="https://originalli.com.br/tela-de-login">Área do cliente ↗</a></nav></div></section>
<section class="inner-section" id="emergencia"><div class="container"><p class="eyebrow dark">Pessoas em primeiro lugar</p><h2>Precisa de ajuda agora?</h2><p>Em risco imediato, acione o serviço público adequado. Não espere o atendimento da corretora.</p><div class="emergency-grid"><a href="tel:190"><span>Polícia Militar</span><strong>190</strong><small>Ligar para emergência policial</small></a><a href="tel:192"><span>SAMU</span><strong>192</strong><small>Ligar para urgência médica</small></a><a href="tel:193"><span>Bombeiros</span><strong>193</strong><small>Ligar para incêndio e resgate</small></a></div><div class="central-support"><div><h3>Assistência do seguro</h3><p>Tenha a apólice em mãos. Serviços dependem das coberturas contratadas.</p></div><a class="button button-primary" href="tel:08004009800">0800 400 9800</a><a class="button button-outline" href="https://wa.me/554333759800" target="_blank" rel="noopener">WhatsApp Originalli</a></div><p class="source-note">Canais públicos: <a href="https://www.policiacivil.pr.gov.br/BO" target="_blank" rel="noopener">Polícia Civil</a> · <a href="https://www.gov.br/saude/pt-br/composicao/saes/samu-192" target="_blank" rel="noopener">Ministério da Saúde</a>.</p></div></section>
<section class="inner-section soft" id="orientacoes"><div class="container"><div class="inner-section-head"><p class="eyebrow dark">Orientação inicial</p><h2>O que aconteceu?</h2><p>Abra somente a orientação de que precisa. Em emergências, siga as instruções dos serviços de socorro.</p></div><div class="guide-columns"><div><h3>Automóvel</h3>
${guide('Colisão', 'Primeiro, procure um local seguro. Havendo feridos, ligue 192 ou 193. Quando não houver risco, reúna informações do evento e dos envolvidos para o aviso à seguradora. Não se exponha para fotografar os danos.')}
${guide('Incêndio no veículo', 'Afaste-se do veículo e ligue 193. Não se aproxime para salvar objetos ou registrar imagens. Depois da liberação das autoridades, contate a assistência e a corretora.')}
${guide('Roubo ou furto', 'Priorize sua segurança. Em risco imediato, ligue 190. Assim que estiver seguro, procure a polícia e comunique o ocorrido à seguradora e à Originalli. Não tente recuperar o bem por conta própria.')}
</div><div><h3>Patrimônio</h3>
${guide('Incêndio no imóvel', 'Saia do local e ligue 193. Siga as orientações dos Bombeiros e aguarde a liberação antes de retornar. Depois, nossa equipe orientará o aviso e os documentos necessários.')}
${guide('Vendaval e danos ao imóvel', 'Mantenha-se longe de estruturas danificadas e fios caídos. Havendo perigo, acione os Bombeiros. Não suba ao telhado para fotografar ou reparar. Quando houver segurança, informe o evento à corretora.')}
${guide('Roubo ou furto de bens', 'Em risco imediato, ligue 190. Quando estiver em segurança, registre a ocorrência pelos canais da polícia. Reúna a relação dos bens e os comprovantes disponíveis para orientação da seguradora.')}
</div><div><h3>Vida e pessoas</h3>
${guide('Falecimento', 'Nossa equipe orientará os familiares na identificação da apólice e no aviso à seguradora. A documentação e a análise de cobertura dependem do contrato. Não envie documentos pessoais por canais públicos.')}
${guide('Acidente, invalidez ou doença grave', 'Priorize o atendimento médico; em urgência, ligue 192. Depois, fale com a Originalli para identificar as coberturas contratadas e o procedimento de aviso. Preserve os documentos do atendimento para envio por canal seguro.')}
${guide('Documentação para o aviso', 'A lista varia conforme o evento e a seguradora. Tenha disponíveis a identificação do segurado, os dados da apólice e as informações do ocorrido. Peça à equipe a relação específica e o canal seguro para envio.')}
</div></div><p class="source-note">Orientação geral, sem garantia de cobertura ou indenização. A análise cabe à seguradora conforme o contrato. Esta página não substitui os serviços de emergência.</p></div></section>
<section class="inner-section" id="fipe"><div class="container central-tools"><div><p class="eyebrow dark">Consulta de veículos</p><h2>Tabela FIPE.</h2><p>Consulte o preço médio de referência de carros, motos e caminhões. O valor não é uma cotação de seguro.</p><a class="text-link" href="https://veiculos.fipe.org.br/" target="_blank" rel="noopener">Consultar diretamente na FIPE ↗</a><p class="source-note">Consulta integrada via API independente de Deivid Fortuna / Parallelum, sujeita à disponibilidade e aos limites do provedor. Confira a referência na fonte oficial.</p></div><form id="fipe-form" class="service-form"><div class="form-row"><label>Tipo<select id="fipe-type" required><option value="">Selecione</option><option value="carros">Carros</option><option value="motos">Motos</option><option value="caminhoes">Caminhões</option></select></label><label>Marca<select id="fipe-brand" required disabled><option value="">Escolha o tipo</option></select></label></div><label>Modelo<select id="fipe-model" required disabled><option value="">Escolha a marca</option></select></label><label>Ano-modelo e combustível<select id="fipe-year" required disabled><option value="">Escolha o modelo</option></select></label><button class="button button-primary" type="submit">Consultar referência</button><p id="fipe-status" role="status" aria-live="polite"></p><div id="fipe-result" hidden></div></form></div></section>
<section class="inner-section soft" id="bo"><div class="container central-tools"><div><p class="eyebrow dark">Canais oficiais</p><h2>Boletim de ocorrência.</h2><p>O registro é feito no portal da polícia, conforme o estado em que o fato ocorreu e o tipo de ocorrência aceito. Em emergência, ligue 190.</p></div><div class="service-form"><label for="bo-uf">Onde ocorreu o fato?</label><select id="bo-uf"><option value="">Selecione o estado</option>${Object.entries({AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins'}).map(([uf,name])=>`<option value="${uf}">${name} — ${uf}</option>`).join('')}</select><p id="bo-note" role="status">Selecione a UF para consultar o encaminhamento disponível.</p><a class="button button-outline" id="bo-link" href="https://www.gov.br/pt-br/servicos/registrar-ocorrencia-policial-online" target="_blank" rel="noopener">Ver orientações oficiais ↗</a><small>O portal federal atende somente estados participantes. Se a UF ou a ocorrência não estiver disponível, procure a Polícia Civil local. A Originalli não registra nem recebe o boletim neste site.</small></div></div></section>
<script src="../central.js" defer></script>`;
