export const insuranceLibrary = [
 ['patrimonial','Patrimonial e empresarial','Empresas, indústrias e comércio','Ajuda a proteger prédios, estoques, móveis e equipamentos contra eventos previstos no contrato.','Avaliar valores de reposição, ocupação, proteção contra incêndio e coberturas como danos elétricos e vendaval.','seguro-patrimonial'],
 ['transportes','Transportes e cargas','Embarcadores e transportadores','O seguro da carga e os seguros de responsabilidade do transportador atendem interesses e responsabilidades diferentes.','Informar mercadorias, rotas, valores, operações e medidas de gerenciamento de riscos.','seguro-transporte'],
 ['frotas','Frotas','Empresas com veículos','Permite organizar a proteção dos veículos da operação e a responsabilidade por danos a terceiros.','Analisar uso, condutores, regiões de circulação, coberturas e assistência.','seguro-frotas'],
 ['responsabilidade-civil','Responsabilidade civil','Empresas e profissionais','Pode amparar responsabilidades por danos a terceiros decorrentes da atividade, conforme a modalidade e as condições contratadas.','Distinguir riscos da operação e da prestação de serviços profissionais; avaliar limites, franquias e regras para reclamações.','responsabilidade-civil'],
 ['do','D&O — administradores','Diretores e gestores','Voltado a reclamações relacionadas a atos de gestão de administradores, nos termos da apólice.','Analisar cargos, estrutura societária, histórico de reclamações, custos de defesa e exclusões.',''],
 ['vida-grupo','Vida em grupo','Empresas e colaboradores','Organiza proteção financeira para colaboradores e beneficiários em situações cobertas pelo seguro.','Avaliar grupo elegível, capitais, coberturas, regras de adesão e obrigações coletivas aplicáveis.','seguro-vida-corporativo'],
 ['beneficios','Benefícios corporativos','Empresas e equipes','Soluções de saúde e odontologia podem compor a política de benefícios da empresa.','Comparar rede, abrangência, elegibilidade, carências, coparticipação e reajustes.','seguro-saude-corporativo'],
 ['engenharia','Riscos de engenharia','Obras e instalações','Voltado a riscos materiais associados à execução de obras e à instalação ou montagem, conforme a contratação.','Apresentar projeto, orçamento, cronograma, características da obra e responsabilidades envolvidas.',''],
 ['maquinas','Máquinas e equipamentos','Indústrias e prestadores de serviços','Proteção de equipamentos usados na operação, em local fixo ou em deslocamento, conforme o produto.','Identificar cada bem, valor, uso, mobilidade, manutenção e riscos de operação.','maquinas-linha-amarela'],
 ['ambientais','Riscos ambientais','Operações com exposição ambiental','Pode contemplar responsabilidades e despesas relacionadas a eventos de poluição cobertos.','Avaliar atividade, locais, substâncias, prevenção, histórico e condições de remediação.',''],
 ['lucros','Lucros cessantes','Negócios que dependem da continuidade operacional','Pode proteger resultados financeiros durante uma paralisação decorrente de dano material coberto, conforme a apólice.','Dimensionar margem, despesas, prazo de recuperação e dependências da operação.',''],
 ['especiais','Operações especiais','Atividades com riscos específicos','Projetos e atividades que exigem uma análise própria para estruturar a proteção.','Conte-nos como funciona a operação, quais bens e responsabilidades estão envolvidos e os contratos existentes.',''],
 ['vida','Vida individual','Pessoas e famílias','Proteção financeira para o segurado e seus beneficiários em eventos previstos no contrato.','Avaliar objetivos, dependentes, capital, coberturas, declaração de saúde e exclusões.','seguro-vida-individual'],
 ['auto','Automóvel','Proprietários de veículos','Reúne alternativas para danos ao veículo, responsabilidade por danos a terceiros e assistência.','Comparar perfil de uso, franquia, limites, oficinas e serviços contratados.','contrate-online'],
 ['residencial','Residencial','Moradores e proprietários','Ajuda a proteger o imóvel e seu conteúdo, com coberturas e assistências selecionadas conforme a necessidade.','Verificar tipo de imóvel, valores, danos elétricos, vendaval, roubo e limites de assistência.','seguro-residencial'],
 ['condominio','Condomínios','Síndicos e administradoras','Proteção das estruturas e áreas comuns, com coberturas adicionais conforme as características do condomínio.','Avaliar edificação, equipamentos, responsabilidades, uso e valores segurados.','seguro-condominio'],
 ['agricolas','Equipamentos agrícolas','Produtores e empresas rurais','Proteção de máquinas e implementos usados na atividade rural, conforme riscos contratados.','Informar modelos, valores, uso, locais e condições de guarda e transporte.','equipamentos-agricolas'],
 ['garantia','Seguro garantia','Empresas com obrigações contratuais','Garante obrigações especificadas no contrato de seguro, dentro dos limites e condições da modalidade.','Analisar contrato principal, obrigação garantida, prazo e documentação da empresa.',''],
 ['fianca','Fiança locatícia','Locadores e locatários','Alternativa de garantia para obrigações do contrato de locação, conforme coberturas aprovadas.','Avaliar aluguel, encargos, prazo, análise cadastral e responsabilidades previstas.',''],
 ['acidentes','Acidentes pessoais','Pessoas e grupos','Proteção para consequências de acidentes pessoais cobertos, conforme definições e garantias da apólice.','Comparar capitais e garantias; esta modalidade não equivale a um seguro com cobertura ampla para doenças.',''],
 ['previdencia','Previdência privada','Pessoas que planejam o futuro','Instrumento de acumulação de recursos para objetivos de longo prazo, sujeito às características do plano escolhido.','Analisar horizonte, perfil, custos, regras de resgate e tributação com orientação adequada.','']
];
export function libraryBody() {
 return `<section class="inner-hero"><div class="container inner-hero-content"><p class="eyebrow">Biblioteca de Seguros</p><h1>Conheça antes de contratar.</h1><p>Entenda as modalidades e descubra quais perguntas fazer para proteger pessoas, patrimônio e operações.</p></div></section><section class="inner-section"><div class="container"><nav class="portfolio-tags" aria-label="Modalidades de seguro">${insuranceLibrary.map(([id,title])=>`<a href="#${id}">${title} →</a>`).join('')}</nav><div class="insurance-library">${insuranceLibrary.map(([id,title,audience,description,review,slug])=>`<article id="${id}" class="library-entry"><p class="eyebrow dark">${audience}</p><h2>${title}</h2><p>${description}</p><h3>O que vale analisar</h3><p>${review}</p><div class="library-actions">${slug?`<a class="text-link" href="/${slug}/">Conhecer a solução →</a>`:''}<a class="button button-primary" href="https://wa.me/554333759800?text=${encodeURIComponent('Olá! Conheci a Biblioteca Originalli e gostaria de orientação sobre '+title+'.')}" target="_blank" rel="noopener">Conversar sobre este seguro</a><a href="#conteudo">Voltar às modalidades ↑</a></div></article>`).join('')}</div><p class="source-note">Conteúdo educativo. Coberturas, limites, franquias, exclusões e aceitação dependem da proposta e das condições de cada seguradora. <a href="https://originalli.com.br/solucoes" target="_blank" rel="noopener">Conheça também as soluções no site institucional anterior.</a></p></div></section>`;
}
