import {can,inScope,requirePermission,profiles,capabilities} from './access.mjs';
import * as XLSX from 'xlsx';
import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
export async function operations({path,req,env,u,url,json,fail,stmt,audit,limitedJSON,policyFor}){
 const root='/api/vida';
 if(path===root+'/permissions'){
  if(u.role!=='admin')fail(403,'Somente a administração pode definir acessos.');
  if(req.method==='GET')return json({profiles,capabilities,users:(await stmt(env,'SELECT u.id,u.name,u.role,u.company_id,p.config FROM life_users u LEFT JOIN life_permissions p ON p.user_id=u.id').all()).results});
  const b=await limitedJSON(req),target=await stmt(env,'SELECT * FROM life_users WHERE id=?',b.id).first();if(!target||target.role==='admin')fail(400,'O administrador principal não pode ser alterado por este painel.');
  if(!profiles[b.role]||b.role==='admin'||!Array.isArray(b.permissions)||b.permissions.some(x=>!capabilities.includes(x))||!Array.isArray(b.companies)||!b.companies.length)fail(400,'Selecione perfil, empresas e permissões.');
  for(const id of b.companies)if(!await stmt(env,'SELECT id FROM life_companies WHERE id=?',id).first())fail(400,'Empresa inválida.');
  const config=JSON.stringify({permissions:[...new Set(b.permissions)],companies:[...new Set(b.companies)]});
  await env.DB.batch([stmt(env,'UPDATE life_users SET role=?,company_id=? WHERE id=?',b.role,b.companies[0],target.id),stmt(env,'INSERT INTO life_permissions(user_id,config) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET config=excluded.config',target.id,config),stmt(env,'DELETE FROM life_sessions WHERE user_id=?',target.id)]);await audit(env,u.id,null,'Permissões alteradas',`${target.username} • ${config}`);return json({ok:true});
 }
 if(path===root+'/deadlines'){
  const p=await policyFor(env,u,url.searchParams.get('policy'));
  if(req.method==='GET')return json(await stmt(env,'SELECT * FROM life_deadlines WHERE policy_id=?',p.id).first());
  if(!['admin','gestor'].includes(u.role))fail(403,'Somente gestão pode definir prazos.');requirePermission(u,'audit');const b=await limitedJSON(req);for(const k of ['rhDay','technicalDay'])if(!Number.isInteger(Number(b[k]))||+b[k]<1||+b[k]>31)fail(400,'Informe dias entre 1 e 31.');if(!Number.isInteger(+b.reminderDays)||+b.reminderDays<0||+b.reminderDays>30)fail(400,'Antecedência inválida.');
  await stmt(env,'INSERT INTO life_deadlines(policy_id,rh_day,technical_day,reminder_days) VALUES(?,?,?,?) ON CONFLICT(policy_id) DO UPDATE SET rh_day=excluded.rh_day,technical_day=excluded.technical_day,reminder_days=excluded.reminder_days',p.id,+b.rhDay,+b.technicalDay,+b.reminderDays).run();await audit(env,u.id,p.id,'Prazos mensais configurados',JSON.stringify(b));return json({ok:true});
 }
 if(path===root+'/transmission'&&req.method==='POST'){
  requirePermission(u,'send');const p=await policyFor(env,u,url.searchParams.get('policy')),b=await limitedJSON(req),month=url.searchParams.get('month');
  const f=await stmt(env,'SELECT * FROM life_files WHERE id=? AND policy_id=? AND competence=?',b.fileId,p.id,month).first();if(!f||f.kind!=='envio')fail(400,'Anexe o comprovante de envio nesta competência antes de registrar.');
  if(!b.protocol||String(b.protocol).length>200||!/^\d{4}-\d{2}-\d{2}$/.test(b.sentAt)||isNaN(Date.parse(b.sentAt))||b.sentAt>new Date().toISOString().slice(0,10)||b.sentAt<p.start)fail(400,'Informe protocolo e data real de envio.');
  const id=crypto.randomUUID();await stmt(env,'INSERT INTO life_transmissions(id,policy_id,competence,file_id,protocol,sent_at,user_id,created) VALUES(?,?,?,?,?,?,?,?)',id,p.id,month,f.id,String(b.protocol),b.sentAt,u.id,new Date().toISOString()).run();await audit(env,u.id,p.id,'Envio à seguradora registrado',`${month} • ${b.sentAt} • ${b.protocol} • comprovante ${f.id}`);return json({ok:true});
 }
 if(path===root+'/monitor'){
  const month=url.searchParams.get('month');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))fail(400,'Competência inválida.');
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const ps=(await stmt(env,'SELECT p.*,c.name company_name,d.rh_day,d.technical_day,d.reminder_days FROM life_policies p JOIN life_companies c ON c.id=p.company_id LEFT JOIN life_deadlines d ON d.policy_id=p.id WHERE substr(p.start,1,7)<=? AND (p.end IS NULL OR substr(p.end,1,7)>=?)',month,month).all()).results.filter(p=>inScope(u,p));const rows=[];
  const due=day=>day?`${month}-${String(Math.min(day,new Date(+month.slice(0,4),+month.slice(5),0).getDate())).padStart(2,'0')}`:null;
  const status=(deadline,done,reminder)=>done?(deadline&&done.slice(0,10)>deadline?'Concluído com atraso':'Concluído'):!deadline?'Prazo não definido':today>deadline?'Em atraso':(Date.parse(deadline)-Date.parse(today))/86400000<=reminder?'Prazo próximo':'Aguardando';
  for(const p of ps){const received=await stmt(env,"SELECT min(created) created FROM life_files WHERE policy_id=? AND competence=? AND kind='movimentacao'",p.id,month).first(),sent=await stmt(env,'SELECT sent_at,protocol FROM life_transmissions WHERE policy_id=? AND competence=? ORDER BY created DESC LIMIT 1',p.id,month).first(),pending=await stmt(env,"SELECT count(*) n FROM life_files WHERE policy_id=? AND competence=? AND kind IN ('movimentacao','base') AND status!='Confirmado'",p.id,month).first();const rhDue=due(p.rh_day),technicalDue=due(p.technical_day);rows.push({id:p.id,company:p.company_name,insurer:p.insurer,number:p.number||'Não informado',month,rhDue,received:received?.created||null,rhStatus:status(rhDue,received?.created,p.reminder_days||0),technicalDue,sent:sent?.sent_at||null,protocol:sent?.protocol||'',technicalStatus:status(technicalDue,sent?.sent_at,p.reminder_days||0),pending:pending.n});}
  const format=url.searchParams.get('format');if(!format){const events=can(u,'audit')?(await stmt(env,'SELECT a.action,a.detail,a.created,a.policy_id,u.name actor FROM life_audit a LEFT JOIN life_users u ON u.id=a.user_id ORDER BY a.created DESC LIMIT 500').all()).results.filter(a=>u.role==='admin'||rows.some(r=>r.id===a.policy_id)).slice(0,100):[];return json({today,rows,events});}requirePermission(u,'audit');requirePermission(u,'export');
  const labels=['Empresa','Seguradora','Apólice','Competência','Prazo RH','Recebido','Situação RH','Prazo técnico','Enviado','Situação técnica','Protocolo','Pendências'];const values=rows.map(r=>[r.company,r.insurer,r.number,r.month,r.rhDue||'',r.received||'',r.rhStatus,r.technicalDue||'',r.sent||'',r.technicalStatus,r.protocol,r.pending]);let bytes;
  if(format==='xlsx'){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([labels,...values]),'Auditoria mensal');bytes=XLSX.write(book,{type:'array',bookType:'xlsx'});}else if(format==='pdf'){const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica);for(let i=0;i<rows.length||i===0;i+=5){const page=doc.addPage([842,595]);page.drawText('ORIGINALLI | Auditoria de Vida em Grupo',{x:35,y:560,size:18,font,color:rgb(.05,.15,.25)});page.drawText(`Competencia: ${month} | Consulta: ${today}`,{x:35,y:535,size:11,font});rows.slice(i,i+5).forEach((r,j)=>{const lines=[`${r.company} | ${r.insurer} | Apólice ${r.number}`,`RH: ${r.rhStatus} | Prazo: ${r.rhDue||'Não definido'} | Recebido: ${r.received?.slice(0,10)||'Não recebido'}`,`Técnico: ${r.technicalStatus} | Prazo: ${r.technicalDue||'Não definido'} | Envio: ${r.sent||'Não registrado'}`,`Protocolo: ${r.protocol||'Não informado'} | Arquivos aguardando conferência: ${r.pending}`];lines.forEach((s,k)=>page.drawText(s.replace(/[^\x20-\xFF]/g,'?').slice(0,120),{x:35,y:500-j*90-k*17,size:10,font}));});page.drawText(`Originalli Corretora de Seguros | originalli@originalli.com.br | Página ${i/5+1}`,{x:35,y:25,size:10,font});}bytes=await doc.save();}else fail(400,'Formato inválido.');await audit(env,u.id,null,'Auditoria gerencial exportada',`${month} • ${format}`);return new Response(bytes,{headers:{'Content-Type':format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="auditoria-${month}.${format}"`,'Cache-Control':'no-store'}});
 }
 return null;
}
