import {access,can,inScope,requirePermission,visibleFile,profiles} from './access.mjs';
import {operations} from './operations.mjs';
import {parseWorkbook,parseRows,workbook,activeRows,validateZip} from './data.mjs';
import {reportPDF} from './report.mjs';
import {publicAPI} from '../integrations/public-api.mjs';
const base='/api/vida',enc=new TextEncoder(),now=()=>new Date().toISOString(),uid=()=>crypto.randomUUID();
const cookieName=env=>env.LOCAL_DEV?'originalli_vida_dev':'__Host-originalli_vida';
const sessionToken=(req,env)=>req.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName(env)+'='))?.slice(cookieName(env).length+1);
const cookie=(v,age,env)=>`${cookieName(env)}=${v}; Path=/; HttpOnly; ${env.LOCAL_DEV?'':'Secure; '}SameSite=Strict; Max-Age=${age}`;
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
const fail=(s,m)=>{throw Object.assign(Error(m),{status:s});};
const hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
export async function hash(s){return hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));}
export async function passwordHash(password,salt=hex(crypto.getRandomValues(new Uint8Array(16)))){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const v=hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256));return salt+':'+v;}
export async function passwordOK(p,h){if(typeof p!=='string'||p.length>200||!h)return false;const actual=await passwordHash(p,h.split(':')[0]);let diff=actual.length^h.length;for(let i=0;i<actual.length;i++)diff|=actual.charCodeAt(i)^(h.charCodeAt(i)||0);return diff===0;}
const strong=p=>typeof p==='string'&&p.length>=12&&p.length<=200;
const stmt=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
async function audit(env,user,policy,action,detail=''){await stmt(env,'INSERT INTO life_audit(id,policy_id,user_id,action,detail,created) VALUES(?,?,?,?,?,?)',uid(),policy||null,user,action,detail,now()).run();}
async function identity(req,env){const token=sessionToken(req,env);if(!token)fail(401,'Entre para continuar.');const u=await stmt(env,'SELECT u.* FROM life_users u JOIN life_sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>? AND u.active=1',await hash(token),Date.now()).first();if(!u)fail(401,'Sessão encerrada. Entre novamente.');return u;}
const admin=u=>{if(u.role!=='admin')fail(403,'Acesso reservado à Originalli.');};
async function policyFor(env,u,id){const p=await stmt(env,'SELECT p.*,c.name company_name,c.cnpj FROM life_policies p JOIN life_companies c ON c.id=p.company_id WHERE p.id=?',id).first();if(!p||!inScope(u,p))fail(404,'Apólice não encontrada.');return p;}
function monthValid(month,p){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||month<p.start.slice(0,7)||(p.end&&month>p.end.slice(0,7)))fail(400,'Competência fora da vigência cadastrada.');}
async function limitedJSON(req){if(Number(req.headers.get('content-length')||0)>2e6)fail(413,'Conteúdo muito grande.');const t=await req.text();if(t.length>2e6)fail(413,'Conteúdo muito grande.');try{return JSON.parse(t);}catch{fail(400,'Dados inválidos.');}}
async function handle(req,env){const url=new URL(req.url),path=url.pathname;
 const publicResponse=await publicAPI(req,env);if(publicResponse)return publicResponse;
 if(!path.startsWith(base)){if(path.startsWith('/api/'))return json({error:'Rota não encontrada.'},404);if(env.ASSETS)return env.ASSETS.fetch(req);return new Response('Não encontrado',{status:404});}
 if(!env.DB||!env.BUCKET)fail(503,'Área em manutenção. Tente novamente em instantes.');
 if(!['GET','HEAD'].includes(req.method)){const origin=req.headers.get('origin');if(origin!==url.origin&&!(path===base+'/bootstrap'&&req.headers.get('x-setup-key')))fail(403,'Origem inválida. Atualize a página.');}
 if(path===base+'/bootstrap'&&req.method==='POST'){
  const key=req.headers.get('x-setup-key');if(!key||!env.LIFE_SETUP_KEY||await hash(key)!==await hash(env.LIFE_SETUP_KEY))fail(403,'Não autorizado.');
  if(await stmt(env,'SELECT id FROM life_users LIMIT 1').first())fail(409,'Implantação já realizada.');
  const b=await limitedJSON(req);if(!strong(b.password))fail(400,'Senha precisa ter ao menos 12 caracteres.');const id=uid();
  await stmt(env,'INSERT INTO life_users(id,username,name,company_id,role,password,must_change,active) VALUES(?,?,?,?,?,?,?,?)',id,'originalli','Gestão Originalli',null,'admin',await passwordHash(b.password),1,1).run();return json({ok:true},201);
 }
 if(path===base+'/login'&&req.method==='POST'){
  const b=await limitedJSON(req);const username=String(b.username||'').trim().toLowerCase();if(username.length>180)fail(400,'Login inválido.');const ip=req.headers.get('cf-connecting-ip')||'unknown';const keys=[await hash('user:'+username),await hash('ip:'+ip)];
  for(const key of keys){const a=await stmt(env,'SELECT * FROM life_attempts WHERE key=?',key).first();if(a&&a.expires>Date.now()&&a.count>=(key===keys[0]?10:50))fail(429,'Muitas tentativas. Aguarde 15 minutos.');await stmt(env,'INSERT INTO life_attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END, expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END',key,Date.now()+900000,Date.now(),Date.now()).run();}
  const u=await stmt(env,'SELECT * FROM life_users WHERE username=? AND active=1',username).first();if(!await passwordOK(b.password,u?.password||'00000000000000000000000000000000:0000000000000000000000000000000000000000000000000000000000000000'))fail(401,'Login ou senha inválidos.');
  const token=hex(crypto.getRandomValues(new Uint8Array(32)));await stmt(env,'INSERT INTO life_sessions(token,user_id,expires) VALUES(?,?,?)',await hash(token),u.id,Date.now()+8*3600000).run();await stmt(env,'DELETE FROM life_attempts WHERE key=?',keys[0]).run();await audit(env,u.id,null,'Entrada');return json({ok:true},200,{'Set-Cookie':cookie(token,28800,env)});
 }
 const u=await access(env,await identity(req,env));
 if(path===base+'/logout'&&req.method==='POST'){const token=sessionToken(req,env);await stmt(env,'DELETE FROM life_sessions WHERE token=?',await hash(token)).run();return json({ok:true},200,{'Set-Cookie':cookie('',0,env)});}
 if(path===base+'/me')return json({name:u.name,role:u.role,permissions:u.permissions,mustChange:!!u.must_change});
 if(path===base+'/password'&&req.method==='POST'){const b=await limitedJSON(req);if(!await passwordOK(b.current,u.password))fail(400,'Senha atual incorreta.');if(!strong(b.password))fail(400,'Use pelo menos 12 caracteres.');await env.DB.batch([stmt(env,'UPDATE life_users SET password=?,must_change=0 WHERE id=?',await passwordHash(b.password),u.id),stmt(env,'DELETE FROM life_sessions WHERE user_id=?',u.id)]);return json({ok:true},200,{'Set-Cookie':cookie('',0,env)});}
 if(u.must_change)fail(403,'Altere sua senha inicial antes de continuar.');
 if(path===base+'/leads'&&req.method==='GET'){admin(u);return json({leads:(await stmt(env,'SELECT l.id,l.name,l.phone,l.profile,l.interest,l.city,l.page,l.created,o.status crm_status,o.attempts FROM site_leads l LEFT JOIN site_outbox o ON o.lead_id=l.id ORDER BY l.created DESC LIMIT 100').all()).results});}
 const operation=await operations({path,req,env,u,url,json,fail,stmt,audit,limitedJSON,policyFor});if(operation)return operation;
 if(path===base+'/policies'&&req.method==='GET'){const sql='SELECT p.*,c.name company_name,c.cnpj FROM life_policies p JOIN life_companies c ON c.id=p.company_id';const result=await stmt(env,sql).all();return json(result.results.filter(p=>inScope(u,p)));}
 if(path===base+'/users'){
  admin(u);
  if(req.method==='GET')return json((await stmt(env,'SELECT u.id,u.username,u.name,u.role,u.active,u.company_id,c.name company_name FROM life_users u LEFT JOIN life_companies c ON c.id=u.company_id ORDER BY u.name').all()).results);
  if(req.method==='POST'){const b=await limitedJSON(req);const username=String(b.username||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(username)||!b.name||(!profiles[b.role]||b.role==='admin')||!await stmt(env,'SELECT id FROM life_companies WHERE id=?',b.companyId).first())fail(400,'Preencha nome, e-mail, empresa e perfil.');const password=hex(crypto.getRandomValues(new Uint8Array(10)));try{await stmt(env,'INSERT INTO life_users(id,username,name,company_id,role,password,must_change,active) VALUES(?,?,?,?,?,?,1,1)',uid(),username,String(b.name).slice(0,150),b.companyId,b.role,await passwordHash(password)).run();}catch{fail(409,'E-mail já cadastrado.');}await audit(env,u.id,null,'Usuário criado',username);return json({username,password});}
 }
 if(path===base+'/user-access'&&req.method==='POST'){admin(u);const b=await limitedJSON(req),target=await stmt(env,'SELECT * FROM life_users WHERE id=?',b.id).first();if(!target||target.role==='admin')fail(400,'Selecione um usuário de empresa.');if(b.action==='reset'){const password=hex(crypto.getRandomValues(new Uint8Array(10)));await env.DB.batch([stmt(env,'UPDATE life_users SET password=?,must_change=1 WHERE id=?',await passwordHash(password),target.id),stmt(env,'DELETE FROM life_sessions WHERE user_id=?',target.id)]);await audit(env,u.id,null,'Senha redefinida',target.username);return json({username:target.username,password});}if(b.action!=='toggle')fail(400,'Ação inválida.');await env.DB.batch([stmt(env,'UPDATE life_users SET active=? WHERE id=?',target.active?0:1,target.id),stmt(env,'DELETE FROM life_sessions WHERE user_id=?',target.id)]);await audit(env,u.id,null,'Acesso alterado',target.username+' • '+(target.active?'bloqueado':'reativado'));return json({ok:true});}
 if(path===base+'/policy'&&req.method==='POST'){admin(u);const b=await limitedJSON(req);if(b.id){await policyFor(env,u,b.id);if(b.end&&(!/^\d{4}-\d{2}-\d{2}$/.test(b.end)||isNaN(Date.parse(b.end))||b.end<(await policyFor(env,u,b.id)).start))fail(400,'Data final inválida.');await stmt(env,'UPDATE life_policies SET number=?,end=?,notes=? WHERE id=?',String(b.number||'').slice(0,100)||null,b.end||null,String(b.notes||'').slice(0,3000),b.id).run();await audit(env,u.id,b.id,'Cadastro de apólice atualizado');return json({ok:true});}if((!b.companyId&&(!b.name||!b.cnpj))||!b.insurer||!/^\d{4}-\d{2}-\d{2}$/.test(b.start)||isNaN(Date.parse(b.start))||(b.end&&b.end<b.start))fail(400,'Preencha empresa, CNPJ, seguradora e início.');const cid=b.companyId||uid(),pid=uid();if(b.companyId&&!await stmt(env,'SELECT id FROM life_companies WHERE id=?',b.companyId).first())fail(400,'Empresa inválida.');await env.DB.batch([...(b.companyId?[]:[stmt(env,'INSERT INTO life_companies(id,name,cnpj,created) VALUES(?,?,?,?)',cid,String(b.name).slice(0,200),String(b.cnpj).slice(0,20),now())]),stmt(env,'INSERT INTO life_policies(id,company_id,insurer,number,start,end,notes,summary) VALUES(?,?,?,?,?,?,?,?)',pid,cid,String(b.insurer).slice(0,150),b.number||null,b.start,b.end||null,'','{}')]);return json({ok:true,id:pid});}
 const p=await policyFor(env,u,url.searchParams.get('policy')||'');const month=url.searchParams.get('month')||p.start.slice(0,7);monthValid(month,p);
 if(path===base+'/month'&&req.method==='GET'){
  const files=(await stmt(env,'SELECT id,competence,kind,name,size,created,status,note,parse_note FROM life_files WHERE policy_id=? AND competence=? ORDER BY created DESC',p.id,month).all()).results;
  const snapshot=await stmt(env,'SELECT * FROM life_snapshots WHERE policy_id=? AND competence=? ORDER BY created DESC,id DESC LIMIT 1',p.id,month).first();const rows=snapshot?activeRows(JSON.parse(snapshot.rows),month):[];
  return json({policy:p,files:files.filter(f=>visibleFile(u,f)),rows:can(u,'roster')?rows:[],snapshot:snapshot?{id:snapshot.id,created:snapshot.created,fileId:snapshot.file_id}:null,history:(await stmt(env,'SELECT competence,count(*) files FROM life_files WHERE policy_id=? GROUP BY competence ORDER BY competence DESC',p.id).all()).results,audit:can(u,'audit')?(await stmt(env,'SELECT action,detail,created FROM life_audit WHERE policy_id=? ORDER BY created DESC LIMIT 80',p.id).all()).results:[]});
 }
 if(path===base+'/upload'&&req.method==='POST'){
  if(Number(req.headers.get('content-length')||0)>11*1024*1024)fail(413,'Limite de 10 MB.');
  const form=await req.formData(),file=form.get('file'),kind=String(form.get('kind')||'movimentacao');if(!file||typeof file.arrayBuffer!=='function'||file.size<1||file.size>10*1024*1024)fail(400,'Selecione um arquivo de até 10 MB.');
  if(!['movimentacao','fatura','boleto','proposta','contrato','apolice','base','envio'].includes(kind))fail(400,'Tipo de documento inválido.');requirePermission(u,kind==='movimentacao'?'movement':['fatura','boleto'].includes(kind)?'billing':kind==='envio'?'send':'documents');
  const ext=file.name.split('.').pop().toLowerCase();if(!(['movimentacao','base'].includes(kind)?['xlsx','xlsm']:['pdf','xlsx','xlsm']).includes(ext))fail(400,'Formato não aceito. Use Excel XLSX/XLSM para movimentação e PDF ou Excel para documentos.');
  const bytes=new Uint8Array(await file.arrayBuffer());if(ext!=='pdf'){try{validateZip(bytes);}catch(e){fail(400,e.message);}}if(ext==='pdf'&&!new TextDecoder().decode(bytes.slice(0,5)).startsWith('%PDF-'))fail(400,'PDF inválido.');
  let rows=null,parseNote='';if(['movimentacao','base'].includes(kind)){try{rows=parseWorkbook(bytes,month);if(!rows.length){rows=null;parseNote='Relação vazia. É necessária conferência.';}}catch(e){parseNote=e.message;}}
  const digest=hex(await crypto.subtle.digest('SHA-256',bytes));const existing=await stmt(env,'SELECT id FROM life_files WHERE policy_id=? AND competence=? AND kind=? AND hash=?',p.id,month,kind,digest).first();if(existing)return json({ok:true,id:existing.id,duplicate:true,message:'Este arquivo já foi recebido nesta competência.'});
  const id=uid(),key=`life/${p.company_id}/${p.id}/${id}`,name=file.name.replace(/[\r\n/\\]/g,'_').slice(0,160);await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:ext==='pdf'?'application/pdf':'application/octet-stream'}});
  try{await stmt(env,'INSERT INTO life_files(id,policy_id,competence,kind,name,size,hash,object_key,user_id,created,status,note,rows,parse_note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,p.id,month,kind,name,file.size,digest,key,u.id,now(),['movimentacao','base'].includes(kind)?'Recebido':'Disponível','',rows?JSON.stringify(rows):null,parseNote).run();}catch(e){await env.BUCKET.delete(key);throw e;}
  await audit(env,u.id,p.id,'Arquivo recebido',`${month} • ${kind} • protocolo ${id}`);return json({ok:true,id,parseNote,message:'Recebido com sucesso pela Originalli. Aguarde a conferência.'},201);
 }
 if(path===base+'/download'&&req.method==='GET'){const f=await stmt(env,'SELECT * FROM life_files WHERE id=? AND policy_id=?',url.searchParams.get('id'),p.id).first();if(!f||!visibleFile(u,f))fail(404,'Arquivo não encontrado.');requirePermission(u,'download');const object=await env.BUCKET.get(f.object_key);if(!object)fail(404,'Arquivo indisponível.');await audit(env,u.id,p.id,'Arquivo baixado',f.name);return new Response(object.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
 if(path===base+'/preview'&&req.method==='GET'){requirePermission(u,'review');const f=await stmt(env,'SELECT rows,parse_note,status FROM life_files WHERE id=? AND policy_id=?',url.searchParams.get('id'),p.id).first();if(!f)fail(404,'Arquivo não encontrado.');return json({...f,rows:f.rows?JSON.parse(f.rows):[]});}
 if(path===base+'/review'&&req.method==='POST'){
  requirePermission(u,'review');const b=await limitedJSON(req),f=await stmt(env,'SELECT * FROM life_files WHERE id=? AND policy_id=? AND competence=?',b.id,p.id,month).first();if(!f||!['movimentacao','base'].includes(f.kind))fail(404,'Movimentação não encontrada.');if(!['Em análise','Pendente','Confirmado'].includes(b.status))fail(400,'Status inválido.');
  if(b.status==='Confirmado'){if(!f.rows)fail(400,'Envie uma relação completa válida no modelo do portal antes de confirmar.');if(!b.confirmation)fail(400,'Confirme a conferência com os documentos da seguradora.');if(!p.number)fail(400,'Cadastre o número da apólice emitida antes de publicar a relação vigente.');const rows=parseRows(JSON.parse(f.rows),month);const last=await stmt(env,'SELECT id FROM life_snapshots WHERE policy_id=? AND competence=? ORDER BY created DESC,id DESC LIMIT 1',p.id,month).first();if((last?.id||'')!==(b.previousSnapshot||''))fail(409,'A relação foi atualizada por outro gestor. Atualize a página e confira novamente.');await env.DB.batch([stmt(env,'INSERT INTO life_snapshots(id,policy_id,competence,file_id,rows,created,user_id) VALUES(?,?,?,?,?,?,?)',uid(),p.id,month,f.id,JSON.stringify(rows),now(),u.id),stmt(env,'UPDATE life_files SET status=?,note=? WHERE id=?','Confirmado',String(b.note||'').slice(0,2000),f.id)]);}else{if(f.status==='Confirmado')fail(400,'Uma relação confirmada é histórica. Envie uma nova versão para corrigir.');await stmt(env,'UPDATE life_files SET status=?,note=? WHERE id=?',b.status,String(b.note||'').slice(0,2000),f.id).run();}
  await audit(env,u.id,p.id,'Conferência: '+b.status,`${month} • protocolo ${f.id} • ${String(b.note||'').slice(0,2000)}`);return json({ok:true});
 }
 if(path===base+'/export'&&req.method==='GET'){
  requirePermission(u,'export');requirePermission(u,'roster');const format=url.searchParams.get('format'),template=url.searchParams.get('template')==='1';let rows=[],created='';if(!template){const s=await stmt(env,'SELECT * FROM life_snapshots WHERE policy_id=? AND competence=? ORDER BY created DESC,id DESC LIMIT 1',p.id,month).first();if(!s)fail(409,'Ainda não existe relação confirmada para esta competência.');rows=activeRows(JSON.parse(s.rows),month);created=s.created;}
  if(!['pdf','xlsx'].includes(format))fail(400,'Formato inválido.');const data=format==='xlsx'?workbook(rows,p,month,template):await reportPDF(rows,p,month,created);await audit(env,u.id,p.id,template?'Modelo baixado':'Relatório exportado',`${month} • ${format}`);return new Response(data,{headers:{'Content-Type':format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="${template?'modelo':'segurados'}-${month}.${format}"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
 }
 fail(404,'Recurso não encontrado.');
}
export default {async fetch(req,env){try{return await handle(req,env);}catch(e){if(!e.status)console.error('Vida portal error',e.message);return json({error:e.status?e.message:'Não foi possível concluir. Seus dados enviados anteriormente continuam preservados. Tente novamente.'},e.status||500);}}};
